version: '3.8'
services:

    nodeapi:
        build:
            context: ./node_api
            dockerfile: Dockerfile
        image: node_api
        container_name: lombaa-node-api
        restart: unless-stopped
        env_file: 
            - ./node_api/.env
        ports:
            - 3001:3001
        depends_on:
            - db
        # networks:
        #     - lombaanet

    laraveladmin:
        build:
            context: ./laravel_admin
            dockerfile: Dockerfile
        image: laravel_admin
        container_name: lombaa-laravel-admin
        restart: unless-stopped
        volumes:
            - ./laravel_admin/:/app/laravel_admin
        # networks:
        #     - lombaanet

    nginx:
        image: nginx:1.17-alpine
        container_name: lombaa-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./laravel_admin:/app/laravel_admin
            - ./docker-compose/nginx:/etc/nginx/conf.d
    #     networks:
    #         - lombaanet

    phpmyadmin:
        image: phpmyadmin
        restart: unless-stopped
        container_name: lombaa-phpmyadmin
        ports:
            - 9000:80
        environment:
            - PMA_ARBITRARY=1

    db:
        image: mysql:8
        platform: linux/x86_64
        container_name: lombaa-db
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: lombaa_dev01
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_USER: lombaa_dev01
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./dbdata:/var/lib/mysql
        # networks:
        #     - lombaanet

networks:
    lombaanet:
        driver: bridge