
GET {{baseUrl}}/category HTTP/1.1
content-type: application/json

###

GET {{baseUrl}}/category/0c725006-069e-4c62-b3cf-d370b70539db/products?search=car HTTP/1.1
Content-Type: application/json
x-app-version : 1.0.0
x-client-platform : Android 