
GET {{baseUrl}}/category HTTP/1.1
content-type: application/json

###

GET {{baseUrl}}/category/903cddcb-0d68-4c79-8d51-6ddcd46258ff/products?lat=20.001273322761&lng=73.791805782892&offset=0&limit=5 HTTP/1.1
Content-Type: application/json
x-app-version : 1.0.0
x-client-platform : Android 