POST  {{baseUrl}}/chat/init HTTP/1.1
content-type: application/json
x-access-token: {{token}}
x-client-platform : Android
x-app-version : 1.0.0

{
    "productId" : "16410714-4e31-4612-a041-2001b5d8465b"
}  

###

POST  {{baseUrl}}/chat/sendMessage HTTP/1.1
content-type: application/json
x-access-token: {{token}}
x-client-platform : Android
x-app-version : 1.0.0

{
    "chatId" : "7f3300ef-9699-4bd8-ba20-3ac0ecb37fb0",
    "text" : "share ur contact details"
}   

###

DELETE  {{baseUrl}}/chat/delete HTTP/1.1 HTTP/1.1
content-type: application/json
x-access-token: {{token}}
x-client-platform : Android
x-app-version : 1.0.0

{
    "id" : "7f3300ef-9699-4bd8-ba20-3ac0ecb37fb0"
}

###

GET {{baseUrl}}/chat/messages?offset=-1&limit=1 HTTP/1.1 HTTP/1.1
content-type: application/json
x-access-token: {{token}}
x-client-platform : Android
x-app-version : 1.0.0

{
    "chatId" : "7f3300ef-9699-4bd8-ba20-3ac0ecb37fb0"
}


# 10000000000000000000
# Check if user is participant for reading chats else show "Invalid Participant".

