@baseUrl = http://localhost:3001/api

GET {{baseUrl}}/locations HTTP/1.1
content-type: application/json

###

GET {{baseUrl}}/locations/7dfd7447-4ab0-11ec-809d-021b0ebe8bee HTTP/1.1
content-type: application/json

###

GET {{baseUrl}}/locations/countries HTTP/1.1
content-type: application/json

###

GET {{baseUrl}}/locations/country/c8912285-4a22-11ec-809d-021b0ebe8bee/regions HTTP/1.1
content-type: application/json

###

GET {{baseUrl}}/locations/region/123/cities HTTP/1.1
content-type: application/json