@baseUrl = http://localhost:3001/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5NzE5NWUzLThkODMtNDY5YS1hMTliLTc3NWE3MmE5NjUzMiIsImlhdCI6MTY0MDk0NjA1NSwiZXhwIjoxNjQxMDMyNDU1fQ.Q2c5_Zpm_wizFJPehHykGMsRSLJGIsJnchX-vtDsjTg

POST {{baseUrl}}/product HTTP/1.1
content-type: application/json
x-client-platform : Android
x-app-version : 1.0.0
x-access-token: {{token}}

{
    "categoryId": "34bac1ec-8d17-467e-936e-0545d222093b",
    "fields": [
        {
            "id": "0149ee22-da43-4ef6-be41-958d7a82d81a",
            "value": {
                "id": "05764cf9-132f-409a-a196-7a0be3766140",
                "value": "Dieselll"
            }
        }
    ],
    "location" : {
        "city": "87a18afa-76dd-4bd6-ada9-789c54a9eef2",
        "region": "af02b759-52d4-11ec-809d-021b0ebe8bee",
        "country": "0f346fe1-5d2e-440f-99eb-eb1703293cdc"
    },
    "media": [
        {
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1OTcxOTVlMy04ZDgzLTQ2OWEtYTE5Yi03NzVhNzJhOTY1MzIiLCJmaWxlSWQiOiI1OTI2NDkwYS03NmQxLTQ1MjQtOTI2Zi0yYzU5YWFiZjQ1NGEiLCJpYXQiOjE2NDA5NDYwNzcsImV4cCI6MTY0MzUzODA3N30.cT9dYGFVJWvfvZGMgE6nPfzXDyG6A2ntRcpZDwwNyaU",
            "isPrimary": true
        }
    ]
}

###

POST  {{baseUrl}}/product/media HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
x-access-token: {{token}}
x-client-platform : Android
x-app-version : 1.0.0

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="media"; filename="video.mp4"
Content-Type: video/mp4

< ./video.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--