POST {{baseUrl}}/product HTTP/1.1
content-type: application/json
x-client-platform : Android
x-app-version : 1.0.0
x-access-token: {{token}}

{
    "categoryId": "",
    "fields": [
        {
            "id": "0149ee22-da43-4ef6-be41-958d7a82d81a",
            "value": {
                "id": "05764cf9-132f-409a-a196-7a0be3766140",
                "value": "Dieselll"
            }
        }
    ],
    "location" : {
        "city": "87a18afa-76dd-4bd6-ada9-789c54a9eef2",
        "region": "af02b759-52d4-11ec-809d-021b0ebe8bee",
        "country": "0f346fe1-5d2e-440f-99eb-eb1703293cdc"
    },
    "media": [
        {
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNmEyMjk5My0yYzVmLTQzMjMtODRlMi00ZDEwNmIwNmY1ZjMiLCJmaWxlSWQiOiIzZjdlMWNiYi03Yzk2LTQxZTQtOTE4OC03NzAxOWFiNWVmMzgiLCJpYXQiOjE2NDE4ODI1OTgsImV4cCI6MTY0NDQ3NDU5OH0.XLQ6rBkssFWKPb2EGGOMbJR06o7U1Y7feo9uJ9LNF_w",
            "isPrimary": true
        }
    ]
}

###

POST  {{baseUrl}}/product/media HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
x-access-token: {{token}}
x-client-platform : Android
x-app-version : 1.0.0

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="media"; filename="video.mp4"
Content-Type: video/mp4

< ./video.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

