@baseUrl = http://localhost:3001/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA5YmJlZTQ4LTU0M2YtNGJjMy1iOTIwLTIwYWMyZTdhZDVlYyIsImlhdCI6MTYzOTIyNjIyMCwiZXhwIjoxNjM5MzEyNjIwfQ.6kfprlklsR492IY-E12oUIK5cikarLWcL1LsJVQ_SS0

POST {{baseUrl}}/product HTTP/1.1
content-type: application/json
x-client-platform : Android
x-app-version : 1.0.0
x-access-token: {{token}}

{
    "categoryId": "34bac1ec-8d17-467e-936e-0545d222093b",
    "fields": [
        {
            "id": "2b335941-5b95-484a-b1b7-581887f75ab0",
            "value": {
                "id": "07eca6df-1bef-4c92-9fcb-c6e81d58baf6",
                "value": "2020"
            }
        }
    ]
}